config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
 
  # get 'static_pages/about' -> this takes you to http://www.example.com/static_pages/about
  # use a named route instead; access by about_path or about_url
  # help_path -> '/help'
  # help_url  -> 'http://www.example.com/help'
  get '/about', to: 'static_pages#about'
  get '/help', to:  'static_pages#help'
  
  # resource routing declares index, show, new, edit, create, update and destroy actions
  # have to individually create each of the views: "show.html.erb" etc.
  # create the methods for each view (.html.erb) in the Users controller file with a method for each view
  # to view user 1, issue a GET request to /users/1
  # the RESTful URLs ensure a POST request to /users is handled by the create action
  resources :users
  
  # the signup page /signup is routed to the new action in the Users controller
  get '/signup', to: 'users#new'
  
  # make a submitted and unsubmitted signup form use the same custom named route
  post '/signup', to: 'users#create'

  # we do not need the full suite of RESTful routes for the Sessions resource
  # session resource uses only named routes 
  # GET and POST requests through login route
  # DELETE request through logout route
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
end

app/views/static_pages/about.html.erb
<% provide(:title, "About | Stacks") %>

<%# this is the body in aplication.hmtl.erb and inserts into <%= yield %/> code %>
<h1>Stacks about page</h1>
<p>
  This is the about page for Stacks.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help | Stacks") %>

<%# this is the body in aplication.hmtl.erb and inserts into <%= yield %/> code %>
<h1>Stacks help page</h1>
<p>
  This is the help page for Stacks.
</p>

app/views/static_pages/home.html.erb
<%# this is the body in application.hmtl.erb and inserts into <%= yield %/> code %>
<% provide(:title, "Stacks") %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="center">
  <h1 class="lead large">Stacks</h1>

  <div class="container">
  	<div class="row">
      <div id="custom-search-input">
        <div class="input-group col-md-4 center">
          <input type="text" class="search-query form-control" placeholder="Enter a symbol or keyword" />
          <span class="input-group-btn">
            <button class="btn btn-danger" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      </div>
  	</div>
  </div>
</div>

<div class="dashboard">
  <%= line_chart(@data1, id: "dow", title: "Dow Jones Industrial Average", colors: ["green"], discrete: false ) %>
  <%= line_chart(@data2, id: "s&p", title: "S&P 500 Index", colors: ["red"] ) %>
  <%= line_chart(@data3, id: "nasd", title: "Nasdaq Composite", colors: ["blue"] ) %>
</div>

<div class="center padding">
  <button type="button" class="btn btn-default btn-lg"><%= link_to "Sign up now!", signup_url %></button>
</div>